# [colors.bright]
# black = "#444747"
# blue = "#6599d5"
# cyan = "#5fbfad"
# green = "#aabb39"
# magenta = "#aa52d5"
# red = "#d3222e"
# white = "#c0c2c2"
# yellow = "#e4bd39"

# [colors.cursor]
# cursor = "#949494"

# [colors.normal]
# black = "#2b2b2b"
# blue = "#a0b9d5"
# cyan = "#91beb6"
# green = "#afba66"
# magenta = "#bf92d5"
# red = "#d35a5f"
# white = "#3b3c3c"
# yellow = "#e5d289"

[colors.primary]
background = "#181818"

[font]
size = 15.0

# cause tsoding
[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

# [font.normal]
# family = "JetBrainsMono Nerd Font"
# style = "Regular"

[font.offset]
x = 0
y = 6

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
decorations = "none"
# decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 1

[window.padding]
x = 3
y = 5

[mouse]
hide_when_typing = true
